### ISSUE TITLE
Tab Navigation Buttons uc.js

### ISSUE THREAD

**Issue by EstherMoellman** [Patchonn/firefox-theme#1]
Hi @Patchonn ,

I'm really in need of a specific JS, and it would be great if you can help me. I'm using the latest version of Firefox Nightly + Windows 10 and, please, I need a JS where a mouse-hovered tab shows (below) the back - reload - forward buttons (inside a small tooltip or popup or container). If the mouse leaves the navigation buttons container or the tab, then the container disappears.

I'm sorry to bother you, but if by chance you can give me a hand... it'll be amazing!
If you don't want to or can't help me, no problem!, I understand, please forget my request.

Thank you in advance!

**Comment by Patchonn** [comment]
Sorry, but I don't plan on working on anything related to Firefox anymore.
